-- this is the complete schema for the database

 -- daily_linkedin_jobs_report
create table public.daily_linkedin_jobs_report (
  id bigint generated by default as identity not null,
  company text null,
  job_title text null,
  job_role text null,
  poster_full_name text null,
  poster_profile_url text null,
  job_url text null,
  company_url text null,
  source text null,
  report_date date null default CURRENT_DATE,
  created_at timestamp with time zone null default now(),
  constraint daily_linkedin_jobs_report_pkey primary key (id)
) TABLESPACE pg_default;




-- password_resets table
create table public.password_resets (
  id uuid not null default gen_random_uuid (),
  user_email text not null,
  reset_token text not null,
  expires_at timestamp with time zone not null,
  used boolean null default false,
  created_at timestamp with time zone null default now(),
  constraint password_resets_pkey primary key (id)
) TABLESPACE pg_default;




-- transactions table
create table public.transactions (
  id uuid not null default gen_random_uuid (),
  user_email text not null,
  order_id text not null,
  transaction_id text null,
  transaction_status text null,
  amount numeric null,
  currency text null default 'USD'::text,
  payer_email text null,
  payer_name text null,
  full_response jsonb null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  full_name text null,
  mobile_number text null,
  country_code text null,
  constraint transactions_pkey primary key (id)
) TABLESPACE pg_default;



-- whopost_users table
create table public.whopost_users (
  user_id uuid not null,
  email text not null,
  full_name text null,
  created_at timestamp with time zone null default now(),
  role text not null default 'whopost_client'::text,
  status boolean not null default false,
  country public.countries not null default 'United States of America'::countries,
  constraint whopost_users_pkey primary key (user_id),
  constraint whopost_users_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint whopost_users_role_check check (
    (
      role = any (
        array['whopost_client'::text, 'whopost_admin'::text]
      )
    )
  )
) TABLESPACE pg_default;

